/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const messages = {
  print: false,
  pattern: 'sys:provider,provider:salesforce',
  allow: { missing: true },

  calls: [
    {
      pattern: 'get:info',
      out: {
        ok: true,
        name: 'salesforce',
        version: Pkg.version,
      },
    },
  ],
}

export default messages

if ('undefined' !== typeof module) {
  module.exports = messages
}
