/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const SalesforceProvider = require('../dist/salesforce-provider')
const SalesforceProviderDoc = require('../dist/SalesforceProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('salesforce-provider', () => {

  it('happy', async () => {
    assert.notEqual(SalesforceProvider, undefined)
    assert.notEqual(SalesforceProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:salesforce,get:info'),
      {
        ok: true,
        name: 'salesforce',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('SalesforceProvider/sdk')()

    assert.equal(typeof sdk.Account, 'function')
  })


  it('account-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/salesforce/account').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/salesforce/account',
    )
  })


  it('account-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/salesforce/account')
      .load$('account0')

    assert.equal(found.id, 'account0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/salesforce/account',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('account-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/salesforce/account')
      .load$('nosuchaccount')

    assert.equal(missing, null)
  })


  it('account-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/salesforce/account')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({  }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/salesforce/account',
    )

    const id = made.id

    try {
      const loaded = await ent.load$({ id: id })
      assert.equal(loaded.id, id)
    }
    finally {
      // Always clean up. The mock and the server both hold data for the
      // process lifetime, so a leaked record changes what later tests see.
      await ent.remove$({ id: id })
    }

    // remove is real: the record is gone, and reading it is an ordinary
    // not-found rather than an error.
    assert.equal(await ent.load$({ id: id }), null)
  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $SALESFORCE_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        salesforce: {
          keys: {
            apikey: { value: '$SALESFORCE_APIKEY' },
          },
        },
      },
    })
    .use(SalesforceProvider, pluginopts)

  return seneca.ready()
}
