/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    account: {
      account0: {},
      account1: {},
    },
  },
}

module.exports = { SEED }
